tests/test_ec2.py, tools/ec2.py
useful when we need to manually share an AMI with another account
=> add share-image command

Makefile, tests/test_sqs.py
When the requirements have changed, then make targets that depend on the virtualenv (eg: test, lint, install, format) will upgrade the virtualenv first.
Before the whole virtualenv was being recreated, which would error when running inside the existing virtualenv. Creating the virtualenv is now split out from upgrading requirements so that its possible to upgrade requirements when make is run within the context of the aec virtualenv.
=> automatically upgrade venv when requirements change

conf/ec2.example.toml, tests/test_ec2.py, tools/ec2.py
Subnets have a MapPublicIpOnLaunch attribute which determines whether instances launched in the subnet receive a public ipv4 address by default.
This PR adds the ability to specify AssociatePublicIpAddress when launching, therefore overriding the default set by the subnet's MapPublicIpOnLaunch attribute.
This is handy if the subnet doesn't by default associate a public IP address and you want one for your instance. Note: the subnet also needs an internet gateway for the public IP address to be accessible.
=> Can specify AssociatePublicIpAddress when launching

tests/test_ec2.py, tools/ec2.py
currently the key_name is specified in the config file
this allows multiple instances to be created easily with different keys
=> add ability to override key name on launch

setup.py, tests/test_ec2.py, tests/test_sqs.py, tools/cli.py, tools/config.py, tools/ec2.py, tools/sqs.py
Don't show the ghost positional argument `args`
(fixes #145)
This is fixed by:
```
wrapper.__signature__ = inspect.signature(func)
```
But in doing so it forces all @arg decorators to reference arguments in
the function signature. Therefore `--profile` can't exist because it
doesn't match a function argument. It has been renamed to `--config`.
Also, because `--config` is optional on the CLI, the function argument
needs to provide a default even though it's mandatory for the function.
Because python syntax doesn't allow non-default arguments to follow
default arguments it has been moved to be the last argument.
=> Don't show the ghost positional argument args

.install-typings-boto3.sh, Makefile, README.md, aec/compute_optimizer.py, aec/display.py, aec/main.py, docs/compute-optimizer.md, docs/compute-optimzer.md, docs/ec2.md, docs/sqs.md, requirements.node.dev.txt, requirements.txt, tests/test_sqs.py, toast.yml
To see the help, run `aec co -h`
```
usage: aec co [-h] {over-provisioned} ...
optional arguments:
-h, --help          show this help message and exit
subcommands:
{over-provisioned}
over-provisioned  Show recommendations for over-provisioned EC2 instances.
```
To show recommendations for over-provisioned instances (eg: idle instances running for more than 30 hours):
```
$ aec co over-provisioned
ID                    Name         Instance Type   Recommendation   Utilization
─────────────────────────────────────────────────────────────────────────────────
i-01579de1b005846cb   instance A   m5.4xlarge      r5.2xlarge       CPU MAX 4.0
i-070c800a592bc6d73   instance B   m5.large        t3.large         CPU MAX 47.0
i-0ad199cc5b65c621d   instance C   m5.xlarge       r5.large         CPU MAX …
```
=> feature: add over-provisioned recommendations

README.md, aec/command/ec2.py, aec/command/ssm.py, aec/main.py, docs/ssm.md, requirements.txt, setup.py
To see the help, run `aec ssm -h`
```
usage: aec ssm [-h] {describe} ...
optional arguments:
-h, --help  show this help message and exit
subcommands:
{describe}
describe  Describe instances running the SSM agent.
```
Example:
```
$ aec ssm describe
ID                    Name                   PingStatus   Platform         AgentVersion
─────────────────────────────────────────────────────────────────────────────────────────
i-01579de1b005846cb   awesome-instance       Online       Amazon Linux 2   2.3.1319.0
i-0f194c8d697f35240   even-better-instance   Online       Ubuntu 20.04     2.3.978.0
```
=> feature: aec ssm describe

aec/command/compute_optimizer.py, docs/compute-optimizer.md
```
$ aec co over-provisioned
ID                    Name         Instance Type   Recommendation   Utilization    Uptime
─────────────────────────────────────────────────────────────────────────────────────────────────────
i-01579de1b005846cb   instance A   m5.4xlarge      r5.2xlarge       CPU MAX 4.0    7 days 8 hours
i-070c800a592bc6d73   instance B   m5.large        t3.large         CPU MAX 47.0   7 days 8 hours
i-0ad199cc5b65c621d   instance C   m5.xlarge       r5.large         CPU MAX 30.0   23 days 8 hours
```
=> feature: co - add uptime

requirements.txt, setup.py, tests/test_compute_optimizer.py
pytz is included as a transitive dev dependency, but was missing from the application deps
bump 0.4.7
=> fix: No module named 'pytz'

aec/main.py
Change from
```
aec ec2 describe --name my-awesome-instance
```
to
```
aec ec2 describe my-awesome-instance
```
This makes ec2 describe consistent with all other commands that take name as a positional argument.
=> change: ec2 describe - name is a positional arg

aec/command/ec2.py, aec/main.py, tests/test_ec2.py
ec2 describe now adds:
```
-q NAME_CONTAINS  Filter to instances with a Name tag containing NAME_CONTAINS (default:
None)
```
=> feat: ec2 describe -q

.github/workflows/pythonapp.yml, .pre-commit-config.yaml
actions/setup-python@v1 bumped the python version to 3.7.9. When this happen the python binary in the cached virtualenv is [borked](https://github.com/seek-oss/aec/runs/1066085039?check_suite_focus=true#step:5:95):
```
~/.virtualenvs/aec/bin/pip install -e '.[dev]'
/bin/bash: /home/runner/.virtualenvs/aec/bin/pip: /home/runner/.virtualenvs/aec/bin/python3: bad interpreter: No such file or directory
Makefile:20: recipe for target '/home/runner/.virtualenvs/aec' failed
```
I've fixed this by using the python version in the cache key to bust the cache.
Also, for some unknown reason, the latest stable version of black (20.8b1) introduces [new formatting changes](https://github.com/seek-oss/aec/runs/1066085039?check_suite_focus=true#step:5:116), so I've pinned it to the old version for now.
=> Fix failing build

.pre-commit-config.yaml, Makefile, requirements.dev.txt, requirements.txt, setup.py
since we use `pip install -e .[dev]` rather than `pip install -r requirements.txt` in the Makefile, we don't really need the requirements.txt files.
=> move requirements into setup.py

.github/workflows/pythonapp.yml
https://github.com/seek-oss/aec/pull/188 removed requirements.txt but the github actions cache uses requirements.* to bust the cache. This PR updates the action to use setup.py instead.
fix broken builds for https://github.com/seek-oss/aec/pull/190 and https://github.com/seek-oss/aec/pull/192
=> bust cache based on setup.py

Makefile, README.md
On a clean install (ie: empty *~/.cache/pip/wheels/*) wheels will need to be built. In this scenario `make install` errors with:
```
error: invalid command 'bdist_wheel'
----------------------------------------
ERROR: Failed building wheel for pyjq
```
Because the virtualenv created by `venv` does not install `wheel` [by design](https://bugs.python.org/issue30628#msg295844):
> It should also be noted that wheel is not installed by venv and must also be installed after the environment creation if needed.
This PR fixes this.
=> fix: install wheel into venv

.flake8, .github/workflows/pythonapp.yml, .gitignore, .pre-commit-config.yaml, Makefile, setup.py
use _./venv/_ for the virtual environment so it can be referenced from the pre-commit hooks. This means flake8 and black only need to be installed in one place (the virtualenv) for use by pre-commit and vscode.
Another advantage is dependabot will automatically keep them up to date.
darglint integrates with flake8, so it doesn't need to be run separately from flake8.
=> refactor: use ./venv/ for virtual environment

src/aec/command/ec2.py, src/aec/main.py, tests/test_ec2.py
because it's not very useful. In particular, for the case where the terminated instance has the same name as a running instance, the start/stop/modify etc. commands will fail because they try to operate on the terminated instance.
=> by default don't show terminated instances

README.md, pyproject.toml, setup.py, src/aec/command/ec2.py, src/aec/config-example/ec2.toml, src/aec/main.py, tests/test_ec2.py
Describe images with a matching name, eg: to describe ubuntu focal images:
```
aec ec2 describe-images -q ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64
```
There is also a new config option `describe_images_name_match`
=> feat: describe images name match

setup.py, src/aec/command/ec2.py, src/aec/config-example/ec2.toml, src/aec/main.py, tests/test_ec2.py
`ec2 launch` now also takes an ami keyword:
```
usage: aec ec2 launch [-h] [--config CONFIG] [--dist {amazon,ubuntu}] [--volume-size VOLUME_SIZE] [--encrypted ENCRYPTED]
[--instance-type INSTANCE_TYPE] [--key-name KEY_NAME] [--userdata USERDATA]
name ami
Launch a tagged EC2 instance with an EBS volume. Specify an AMI keyword to select the latest AMI for that distro and version.
positional arguments:
name                  Name tag of instance
ami                   AMI id or a one of the keywords ['amazon2', 'ubuntu1604', 'ubuntu1804', 'ubuntu2004']
```
Based on the keyword, it will select the latest version of the relevant distro's x86_64 SSD AMI. This saves the user from having to look up the ami id each time.
=> feat: select latest ami based on keyword

docs/ec2.md, setup.py, src/aec/command/ec2.py, src/aec/main.py
Remove the `--dist` argument from `ec2 launch` and look up the correct root device name from the AMI rather than relying on the user to specify it.
I recently created an ubuntu instance and forgot to specify `--dist ubuntu`. This meant my EBS volume was never mounted.
This change makes this error impossible.
=> feat: remove dist arg and lookup root device from the ami

setup.py, src/aec/command/ec2_images.py, src/aec/command/ec2_instances.py, src/aec/main.py, tests/test_compute_optimizer.py, tests/test_ec2_images.py, tests/test_ec2_instances.py
ec2.py was getting long, so I've split its functionality into ec2_images & ec2_instances
=> refactor: split ec2 module into ec2_images & ec2_instances

README.md, docs/ami.md, docs/compute-optimizer.md, docs/ec2.md, docs/ssm.md, setup.py, src/aec/command/ami.py, src/aec/command/ec2.py, src/aec/main.py, tests/test_ami.py, tests/test_compute_optimizer.py, tests/test_ec2.py
Splits out the ami related commands into their own subcommand `aec ami`:
```
usage: aec ami [-h] {delete,describe,share} ...
optional arguments:
-h, --help            show this help message and exit
subcommands:
{delete,describe,share}
delete              Deregister an AMI and delete its snapshot.
describe            List AMIs.
share               Share an AMI with another account.
```
=> feat: ami subcommand

docs/ec2.md, setup.py, src/aec/command/ec2.py, src/aec/main.py, tests/test_ec2.py
Allow an instance id to be used where name is, eg:
```
ec2 terminate i-06814ad77d5177e5a
```
=> feat: instance id as name

docs/ami.md, src/aec/command/ec2.py, tests/test_ec2.py
If EBS optimized is enabled and you change the instance type to t2.*, when starting the instance this error occurs:
```
An error occurred (Unsupported) when calling the StartInstances operation: The requested configuration is currently not supported. Please check the documentation for supported configurations.
```
This PR fixes this.
=> fix: set correct ebs optimized settings when modifying type

src/aec/command/ami.py
some of the Canonical images don't have a RootDeviceName and threw
KeyError: 'RootDeviceName'
so we now handle this edge case
=> fix: ami - handle missing RootDeviceName

package-lock.json, package.json, setup.py
=> chore: remove importlib_metadata (no longer needed as explicit dep)

setup.py
Boto3 doesn't seem to be installed through a fresh install
```
$ aec ec2  --h
ModuleNotFoundError: No module named 'boto3'
```
Also `boto3-stubs` makes more sense as a dev dependency since it's an editor plug in
=> Add boto3 to dependencies

README.md
It seems like `pipx` doesn't play nice if we try to install it from within a virtual environment
Also I think it's better to have `pip` in the instruction since it's a standard tool. `pipx` can be a personal choice since it might not work on every kind of set up.
=> Update README to use pip instead of pipx

.flake8, .github/workflows/pythonapp.yml, .gitignore, .pre-commit-config.yaml, Makefile, pyproject.toml
Change the virtualenv location from _venv/_ to _.venv/_.
dot dirs are automatically excluded by many cli tools (eg: fzf, rg) and most of the time we want to ignore the contents of the virtual env.
=> use .venv/ instead of venv/

src/aec/command/ec2.py
create gp3 volumes instead of gp2
gp3 vs gp2:
* 20% lower price
* 4x max throughput & burstable capacity
https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/
=> feat: create gp3 volumes

docs/ec2.md, setup.py, src/aec/command/ec2.py, src/aec/main.py, tests/test_cli.py, tests/test_ec2.py
`ec2 create-key-pair` creates a new key pair and saves the private key to the local disk
=> feat: create key pair

src/aec/command/ec2.py
Show helpful error message instead of stacktrace when logs aren't available, eg:
```
$ ec2 logs oliver
No logs yet 😔
```
=> fix: no logs yet

docs/ec2.md, src/aec/main.py, src/aec/util/cli.py, src/aec/util/display.py, tests/test_display.py
Show output as csv instead of a table (works with any command)
```
ec2 tags -v -o csv
VolumeId,Name,Tags
vol-0439c5ed37f6d455e,awesome-vol,"Name=awesome-vol, Owner=jane"
```
refactor: remove pretty_table because it's not being used
=> feat: csv output

src/aec/command/ami.py, src/aec/command/compute_optimizer.py, src/aec/command/ec2.py, src/aec/util/display.py, src/aec/util/tags.py
`from __future__ import annotations` will [treat annotations as strings at runtime](https://adamj.eu/tech/2021/05/15/python-type-hints-future-annotations/)
This fixes:
```
$ aec co over-provisioned
Traceback (most recent call last):
File "/Users/tekumara/code/aec/.venv/bin/aec", line 33, in <module>
sys.exit(load_entry_point('aec-cli', 'console_scripts', 'aec')())
File "/Users/tekumara/code/aec/src/aec/main.py", line 134, in main
result = cli.dispatch(build_parser(), args)
File "/Users/tekumara/code/aec/src/aec/util/cli.py", line 87, in dispatch
return call_me(**vars(pargs))
File "/Users/tekumara/code/aec/src/aec/command/compute_optimizer.py", line 17, in over_provisioned
def util(metric: UtilizationMetricTypeDef) -> str:
NameError: name 'UtilizationMetricTypeDef' is not defined
```
It …
=> fix: NameError: name 'UtilizationMetricTypeDef' is not defined

package.json, setup.py, src/aec/command/ec2.py
using InstanceTypeType literal introduced in https://github.com/vemel/mypy_boto3_builder/issues/71
also bump to latest version of pyright + boto + boto stubs
=> fix: Could not assign item in TypedDict Type "str" cannot be assigned to type "InstanceTypeType"

Makefile, pyproject.toml, setup.py
Add [packaging requirements](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#package-requirement) using `build-system` (ie: [PEP 517](https://www.python.org/dev/peps/pep-0517/) style) 
This tells `pip install` to install setuptools and wheel if they are not present when installing the package. For more info see https://github.com/tekumara/python-typed-template/commit/74b8e90a839aa141d3af15fa562d646ba3a50f50
=> refactor: add packaging requirements using build-system (ie: pep517 build)

src/aec/command/ec2.py
Commit through Github UI did not get format checked and master build failed. Minor addition of whitespace.
=> re-format warning message to pass tests

Makefile, docs/ami.md, docs/compute-optimizer.md, docs/ec2.md, docs/ssm.md, setup.py, src/aec/main.py
use [cog](https://github.com/nedbat/cog) to automate the generation of the help snippets in the docs
=> build: use cog to generate help docs

MANIFEST.in
sdist and wheels don't normally include `__pycache__/*.pyc` files, which were being included by `graft src`.
by being more selective they will no longer be included.
=> build: don't include .pyc files

.github/workflows/pythonapp.yml, pyproject.toml, toast.yml
also fixes the build cache and toast.yml to use pyproject.toml introduced in #372
=> chore: bump deps

.github/workflows/pythonapp.yml
so we can run CI on forks, eg: https://github.com/seek-oss/aec/pull/381
NB: still requires approval for outside collaborators to prevent untrusted code from running, see [Approving workflow runs from public forks](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
=> build: enable ci on pull request

src/aec/util/config.py
The describe_images_owners key is either a string or a List of string. Logic for both cases is in https://github.com/seek-oss/aec/blob/master/src/aec/command/ami.py#L76-L83, and usage is illustrated by the example at https://github.com/seek-oss/aec/blob/master/src/aec/config-example/ec2.toml.
This fix is required on my side to allow easily reading the AEC conf with pydantic.
=> Correctly type describe_images_owners in config

.github/workflows/pythonapp.yml
the fix in #375 didn't work.. from the [failed build](https://github.com/seek-oss/aec/runs/7606810567?check_suite_focus=true#step:10:10):
```
Run echo "version=$(python -c 'import aec;print(aec.__version__)')" >> $GITHUB_ENV
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'aec'
```
=> build: fix tagging again

docs/ec2.md, docs/ssm.md, src/aec/command/ec2.py, src/aec/main.py, src/aec/util/cli.py, src/aec/util/display.py, src/aec/util/docgen.py, src/aec/util/docs.py, tests/test_ec2.py
also now derives cli argparser defaults from function parameter defaults to avoid drift (I discovered the drift when running `ec2 describe` via cog)
=> docs: use cog to generate ec2 describe docs

pyproject.toml
[ruff now only supports 3.7+](https://github.com/charliermarsh/ruff/pull/2159) and errors with a lower target version
Dropping python 3.6 support is OK, as it's [EOL](https://endoflife.date/python), and no longer a supported AWS Lambda runtime. It still ships with Ubuntu 18.04 but that is [EOL in April 2023](https://canonical.com/blog/ubuntu-18-04-lts-end-of-life-keep-your-fleet-of-devices-up-and-running).
=> feat: python 3.7 is now the minimal version

.github/release-drafter.yml, src/aec/command/ami.py, src/aec/command/ec2.py, src/aec/command/ssm.py, src/aec/main.py, tests/test_ami.py, tests/test_ec2.py
because `name` can be a `Name` tag or the object `id`
see [this discussion](https://github.com/seek-oss/aec/pull/419#discussion_r1137905001)
=> refactor: rename name to ident

pyproject.toml
[ruff 0.0.255](https://github.com/charliermarsh/ruff/releases/tag/v0.0.255) now infers target version from `requires-python`
=> chore: bump ruff

src/aec/main.py
fixes:
```
❯ aec ec2 logs my-instance
Traceback (most recent call last):
File "/Users/oliver.mannion/code/aec/.venv/bin/aec", line 8, in <module>
sys.exit(main())
File "/Users/oliver.mannion/code/aec/src/aec/main.py", line 213, in main
result, output_format = cli.dispatch(build_parser(), args)
File "/Users/oliver.mannion/code/aec/src/aec/util/cli.py", line 103, in dispatch
return (call_me(**vars(pargs)), output_format)
TypeError: logs() got an unexpected keyword argument 'name'
```
=> fix: TypeError: logs() got an unexpected keyword argument 'name'

Makefile, pyproject.toml
tell pyright where to find the venv so we don't need to have it activated for type checking to find imports
plus it looks a little cleaner
=> refactor: specify venv in pyright config

pyproject.toml, src/aec/command/ami.py, src/aec/command/compute_optimizer.py, src/aec/command/ec2.py, src/aec/command/ssm.py, src/aec/util/display.py, src/aec/util/docgen.py, src/aec/util/ec2.py, src/aec/util/ec2_types.py, src/aec/util/tags.py
includes updates to address the breaking change in https://github.com/charliermarsh/ruff/pull/4427 and fixes for the now enabled rules:
- UP006 (non-pep585-annotation)
- UP007 (non-pep604-annotation)
=> chore: upgrade to ruff 0.0.270

tests/conftest.py
fixes:
```
make test
...
.venv/lib/python3.9/site-packages/botocore/credentials.py:547: RuntimeError
----------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------
WARNING  botocore.credentials:credentials.py:546 Credentials were refreshed, but the refreshed credentials are still expired.
==================================================================== short test summary info =====================================================================
FAILED tests/test_ami.py::test_describe_images - RuntimeError: Credentials were refreshed, but the refreshed credentials are still expired.
FAILED tests/test_ami.py::test_describe_images_by_id - RuntimeError: Credentials were refreshed, but the …
```
=> fix: avoid stale creds in tests

.github/workflows/release.yml, docs/ami.md, docs/ec2.md, pyproject.toml, src/aec/command/ec2.py, tests/test_ec2.py
via the `Image.` prefix
eg: to see how old the image used by an instance is, use the column `Image.CreationDate`
```
aec ec2 describe -c Name,SubnetId,Volumes,Image.CreationDate
Name    SubnetId          Volumes           Image.CreationDate  
──────────────────────────────────────────────────────────────────────
alice   subnet-3f674ae5   ['Size=15 GiB']   2023-05-27T03:17:09.000Z  
sam     subnet-3f674ae5   ['Size=15 GiB']   2023-05-27T03:17:09.000Z
```
=> feat: `ec2 describe` can return columns about the ami

MANIFEST.in
as its not needed when using setuptools-scm
=> chore: remove MANIFEST.in

pyproject.toml, src/aec/command/ec2.py, src/aec/main.py, src/aec/util/cli.py, src/aec/util/config.py, src/aec/util/errors.py, tests/test_cli.py, tests/test_ssm.py
Fixes:
* FA100 Missing `from __future__ import annotations`, but uses `typing.Optional`
* UP006 (non-pep585-annotation)
* UP007 (non-pep604-annotation)
=> chore: bump ruff 0.0.282

.pre-commit-config.yaml, Makefile, pyproject.toml
to remove knowledge of .venv (which is determined by the Makefile) from the pre-commit hooks 
this also seems to be more canonical (eg: [black](https://black.readthedocs.io/en/stable/integrations/source_version_control.html), [ruff](https://github.com/astral-sh/ruff-pre-commit))
originally they were local so we could use them:
1.  in the makefile, but `make check` now calls pre-commit
1.  in vs code, which used to require they be installed in the venv, but now the [black extension](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) bundles a version (as the ruff extension always did)
the trade-off is that we won't have version parity between vs code and pre-commit (likewise, we don't already have this between pyright and pylance)
=> ci: refactor to use ruff and black non-local hooks

src/aec/main.py
Instead of a stacktrace now shows:
```
NoRegionError: You must specify a region..
Authenticate with the appropriate AWS role before retrying.
```
=> feat: nicer error message for NoRegionError

.cruft.json, .gitignore, .pre-commit-config.yaml, Makefile, Makefile-common.mk, pyproject.toml, src/aec/command/ami.py, src/aec/command/compute_optimizer.py, src/aec/command/ec2.py, src/aec/main.py, src/aec/util/cli.py, src/aec/util/display.py, toast.yml
align with [python-typed-template](https://github.com/tekumara/python-typed-template/tree/518252bdc6eaa21043b929e074a03c1da6126db2)
ruff is now installed into the venv rather than as a pre-commit hook, reversing #443 and reintroducing knowledge of .venv into .pre-commit-config.yaml. This is advantageous until [Dependabot supports updating pre-commit hooks](https://github.com/dependabot/dependabot-core/issues/1524) and also means `ruff check .` can be run locally.
toast: install hooks during install step so they are cached
=> chore: align with python-typed-template 

.github/workflows/ci.yml, Makefile-common.mk, toast.yml
curl -LsSf https://astral.sh/uv/install.sh | sh
real    0m5.687s
user    0m0.434s
sys     0m0.180s
uv pip install
real    0m13.621s
user    0m2.195s
sys     0m1.532s
pip install
real    0m27.810s
user    0m14.600s
sys     0m1.172s
make install (pip install) 34s
make install (install uv + uv pip install) 10s
=> ci: add uv

src/aec/command/ec2.py, tests/test_ec2.py
makes this distinct from NoInstancesError to make it more obvious
=> refactor: missing identifier guard

src/aec/command/ec2.py, src/aec/main.py
before:
```
❯ aec ec2 terminate ""
Traceback (most recent call last):
File "/Users/oliver.mannion/code/aec/.venv/bin/aec", line 10, in <module>
sys.exit(main())
File "/Users/oliver.mannion/code/aec/src/aec/main.py", line 233, in main
result, output_format = cli.dispatch(build_parser(), args)
File "/Users/oliver.mannion/code/aec/src/aec/util/cli.py", line 105, in dispatch
return (call_me(**vars(pargs)), output_format)
File "/Users/oliver.mannion/code/aec/src/aec/command/ec2.py", line 476, in terminate
raise ValueError("Missing instance identifier")
ValueError: Missing instance identifier
```
after:
```
❯ aec ec2 terminate ""
usage: aec ec2 terminate [-h] [--config CONFIG] [-o {table,csv}] ident
aec ec2 terminate: error: argument ident: is empty string
```
also simplifies the code
=> refactor: empty string identifier guard again
