seek-oss/aec

- .github/workflows/pythonapp.yml
- tests/test_sqs.py
- tools/sqs.py
Add github action that runs tests on every push
> Add github action

- .github/workflows/pythonapp.yml
> Cache build

- setup.py
> use pathlib in setup.py

- docs/ec2.md
- docs/sqs.md
- tools/ec2.py
due to changes in https://github.com/seek-oss/aec/pull/161
> update docs after replacing argh

- tools/main.py
* Fix missing argument bug introduced by https://github.com/seek-oss/aec/pull/165
* Fix arguments being parsed as string introduced by https://github.com/seek-oss/aec/pull/161
> Fix argument bugs

- aec/command/ec2.py
- aec/main.py
- docs/ec2.md
- setup.py
- tests/test_ec2.py
`aec ec2 logs instance_name` shows the system logs (aka console output)
> feature: ec2 logs

- .gitignore
- aec/command/ec2.py
- requirements.txt
includes fix for https://github.com/vemel/mypy_boto3_builder/issues/45
> bump boto3 1.14.52.1

- .pre-commit-config.yaml
- aec/command/sqs.py
- tests/test_sqs.py
> bump hooks to latest versions

- aec/command/sqs.py
- package-lock.json
- package.json
bump pyright 1.1.67 with fix for https://github.com/microsoft/pyright/issues/1008
> bump pyright 1.1.67

- .flake8
- .pre-commit-config.yaml
- aec/command/ec2.py
- aec/util/cli.py
- aec/util/config.py
- aec/util/configure.py
- aec/util/display.py
- setup.py
add flake8 check that functions have type annotations
fix missing annotations
> test: functions must have type annotations

- .pre-commit-config.yaml
- Makefile
- pyproject.toml
- pyrightconfig.json
- setup.py
add isort to venv so it can be run via `make format`
> local isort

- docs/ec2.md
- src/aec/command/ec2.py
- src/aec/main.py
- tests/test_ec2.py
Show running or pending instances only:
```
ec2 describe -r
```
> feat: show running instances only

- src/aec/util/display.py
> feat: print Done instead of None

- README.md
- docs/ec2.md
- src/aec/command/ec2.py
- src/aec/command/ssm.py
- src/aec/main.py
- src/aec/util/tags.py
- tests/test_ec2.py
Show volume tags
```
ec2 tags -v
VolumeId              Name          Tags
───────────────────────────────────────────────────────────────────
i-099fe44f811245812   awesome-vol   Name=awesome-vol, Owner=jane
```
> feat: volume tags

- Makefile
- setup.py
- src/aec/command/ssm.py
in doing so needed to fix:
```
ssm.py:271:43 - error: Argument of type "StreamingBody" cannot be assigned to parameter "stream" of type "IO[bytes]" in function "__call__"
"StreamingBody" is incompatible with "IO[bytes]" (reportGeneralTypeIssues)
```
> chore: bump boto 1.17.93

- docs/ec2.md
- src/aec/command/ec2.py
- src/aec/main.py
- tests/test_ec2.py
Show running instances sorted by date started (ie: LaunchTime), oldest first:
```
ec2 describe -r -s LaunchTime
```
> feat: ec2 describe sort by

- src/aec/command/ec2.py
- src/aec/main.py
- src/aec/util/error.py
also print a stack trace for an unhandled ClientError
> refactor: no stacktraces for known errors that can be handled

- .flake8
- docs/ssm.md
- src/aec/command/ec2.py
- src/aec/command/ssm.py
- src/aec/main.py
- src/aec/util/display.py
- src/aec/util/ec2.py
eg: List running instances containing `gaga` in the name:
```
aec ssm describe -q gaga
```
> feat: ssm describe with name filters

- .pre-commit-config.yaml
- Makefile
- package.json
- pyproject.toml
the autoflake hook will remove unused imports
> build: add autoflake + bump pyright

- .pre-commit-config.yaml
- Makefile
- pyproject.toml
- src/aec/command/ssm.py
DRY autoflake config into pyproject.toml
install docformatter into venv and DRY its config into pyproject.toml
> build: DRY autoflake config + add docformatter to venv

- .github/workflows/pythonapp.yml
- .pre-commit-config.yaml
- Makefile
- pyproject.toml
use https://github.com/crate-ci/typos to check for typos and add ruff rules
> build: add typos check + ruff rules

- .github/release-drafter.yml
- .github/workflows/drafter.yml
- .pre-commit-config.yaml
- _typos.toml
- docs/ami.md
- docs/ec2.md
- src/aec/command/ami.py
- src/aec/main.py
- src/aec/util/docgen.py
- tests/test_ami.py
eg:
```
❯ ami describe "AWS Deep Learning Base AMI GPU CUDA 11 (Ubuntu 20.04) 20230314"
Describing images owned by ['self', '099720109477', '898082745236'] named AWS Deep Learning Base AMI GPU CUDA 11 (Ubuntu 20.04) 20230314
Name                                                             ImageId                 CreationDate               RootDeviceName   Size  
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
AWS Deep Learning Base AMI GPU CUDA 11 (Ubuntu 20.04) 20230314   ami-0a50ae3a720737240   2023-03-15T11:10:41.000Z   /dev/sda1        100   
```
> feat: ami describe by name

- .darglint
- .pre-commit-config.yaml
- docs/ec2.md
- src/aec/command/ec2.py
- src/aec/util/display.py
- tests/test_display.py
- tests/test_ec2.py
eg:
```
❯ ec2 describe -c Name,Volumes
Name                 Volumes           
─────────────────────────────────────── 
the-fresh-instance   ['Size=140 GiB']  
```
> feat: ec2 describe volumes

- Makefile
- package.json
- pyproject.toml
- toast.yml
resolves https://github.com/seek-oss/aec/security/dependabot/1
> chore: bump deps

- setup.py
as its not needed with the newer versions of pip
> chore: remove setup.py

- docs/ami.md
- docs/ec2.md
- src/aec/command/ec2.py
- src/aec/main.py
- src/aec/util/tags.py
- tests/test_ec2.py
```
aec ec2 subnets
SubnetId          VpcId          AvailabilityZone   CidrBlock        Name  
───────────────────────────────────────────────────────────────────────────
subnet-8ffb733b   vpc-df045ae9   us-east-1a         172.31.0.0/20  
subnet-50f11bb4   vpc-df045ae9   us-east-1b         172.31.16.0/20  
subnet-93811557   vpc-df045ae9   us-east-1c         172.31.32.0/20  
subnet-f17e6261   vpc-df045ae9   us-east-1d         172.31.48.0/20  
subnet-1a5d6685   vpc-df045ae9   us-east-1e         172.31.64.0/20  
subnet-b12557cf   vpc-df045ae9   us-east-1f         172.31.80.0/20
```
> feat: add subnets

- src/aec/command/ssm.py
by iterating through the paged response
> fix: compliance summary now shows more than 50 instances

- docs/ami.md
- docs/ec2.md
- src/aec/command/ec2.py
- src/aec/main.py
- tests/test_ec2.py
eg:
```shell
aec ec2 start instance1 instance2
```
> feat: start multiple instances at once

- .typos.toml
- docs/ami.md
- docs/ec2.md
- docs/ssm.md
- src/aec/command/ec2.py
- src/aec/main.py
- tests/test_ec2.py
eg: termination now asks for confirmation
```
aec ec2 terminate alice bob
The following instances will be terminated:
- alice (i-e486a95800887c6f6)
- bob (i-d1ca88511b58cc3fc)
Are you sure you want to terminate these instances? (y/n): y
State           InstanceId           
───────────────────────────────────── 
shutting-down   i-e486a95800887c6f6
shutting-down  i-d1ca88511b58cc3fc
```
or without the prompt
```
aec ec2 terminate delme -y
The following instances will be terminated:
- delme (i-0cc42e159e2dd518b)
State           InstanceId           
───────────────────────────────────── 
shutting-down   i-0cc42e159e2dd518b  
```
> feat! terminate multiple instances + ask for confirmation
